# Default admittance controller parameters

# Impedance outer loop
limit_error: true
limit_torques: true
max_delta_tau: 2.0
nullspace.stiffness: 5.0
stop_commands: false

task.k_pos_x: 900.0
task.k_pos_y: 900.0
task.k_pos_z: 900.0
task.k_rot_x: 45.0
task.k_rot_y: 45.0
task.k_rot_z: 45.0

task.d_pos_x: 60.0
task.d_pos_y: 60.0
task.d_pos_z: 60.0
task.d_rot_x: 10.0
task.d_rot_y: 10.0
task.d_rot_z: 10.0

task.error_clip.rx: 0.5
task.error_clip.ry: 0.5
task.error_clip.rz: 0.5
task.error_clip.x: 0.1
task.error_clip.y: 0.1
task.error_clip.z: 0.1

use_coriolis_compensation: true
use_friction: true
use_gravity_compensation: false
use_local_jacobian: true
use_operational_space: false

# Admittance parameters (virtual MSD)
admittance.mass_x: 1.0
admittance.mass_y: 1.0
admittance.mass_z: 1.0
admittance.mass_rx: 0.1
admittance.mass_ry: 0.1
admittance.mass_rz: 0.1
admittance.stiffness_x: 200.0
admittance.stiffness_y: 200.0
admittance.stiffness_z: 200.0
admittance.stiffness_rx: 10.0
admittance.stiffness_ry: 10.0
admittance.stiffness_rz: 10.0
admittance.damping_x: 50.0
admittance.damping_y: 50.0
admittance.damping_z: 50.0
admittance.damping_rx: 5.0
admittance.damping_ry: 5.0
admittance.damping_rz: 5.0

# F/T sensor
ft_sensor.topic: "ft_sensor_wrench"
