filter.dq: 0.5
filter.output_torque: 0.5
filter.q: 0.5
filter.target_pose: 0.1

friction.fp1:
- 0.54615
- 0.87224
- 0.64068
- 1.2794
- 0.83904
- 0.30301
- 0.56489
friction.fp2:
- 5.1181
- 9.0657
- 10.136
- 5.5903
- 8.3469
- 17.133
- 10.336
friction.fp3:
- 0.039533
- 0.025882
- -0.04607
- 0.036194
- 0.026226
- -0.021047
- 0.0035526

limit_error: true
limit_torques: true

max_delta_tau: 0.5

# nullspace stiffness is set to 0 but a different value might make more sense to keep the arm upright.
nullspace.stiffness: 5.0
nullspace.damping: 1.0
nullspace.max_tau: 5.0
nullspace.projector_type: none
nullspace.regularization: 1.0e-06
nullspace.weights.right_fr3_joint1.value: 15.0
nullspace.weights.right_fr3_joint2.value: 15.0
nullspace.weights.right_fr3_joint3.value: 8.0
nullspace.weights.right_fr3_joint4.value: 8.0
nullspace.weights.right_fr3_joint5.value: 8.0
nullspace.weights.right_fr3_joint6.value: 5.0
nullspace.weights.right_fr3_joint7.value: 5.0

stop_commands: false

# We set the task gains to 0
task.k_pos_x: 0.0
task.k_pos_y: 0.0
task.k_pos_z: 0.0
task.k_rot_x: 0.0
task.k_rot_y: 0.0
task.k_rot_z: 0.0
task.d_pos_x: -1.0
task.d_pos_y: -1.0
task.d_pos_z: -1.0
task.d_rot_x: -1.0
task.d_rot_y: -1.0
task.d_rot_z: -1.0

task.error_clip.rx: 0.5
task.error_clip.ry: 0.5
task.error_clip.rz: 0.5
task.error_clip.x: 0.1
task.error_clip.y: 0.1
task.error_clip.z: 0.1

use_coriolis_compensation: true
use_friction: true
use_gravity_compensation: false
use_local_jacobian: true
use_operational_space: false
use_sim_time: false
